const products=[
 {id:1,name:'Alfred Gratien Brut Classique',type:'Шампанское',price:0,time:'Франция · 0,75 л',desc:'Мёд, цитрусовые, манго, персик и абрикос',tone:'cedar',image:'https://aroma.ru/uploads/gss/goods/1243/01b_1.jpg',url:'https://aroma.ru/produktsiya/igristoe-vino-i-shampanskoe/alfred-graten-bryut-klassik-alfred-gratien-brut-classique/'},
 {id:2,name:'Alfred Gratien Grand Cru',type:'Шампанское',price:0,time:'Франция · 0,75 л',desc:'Лайм, лимонник, жасмин, миндаль',tone:'santal',image:'https://aroma.ru/uploads/gss/goods/1243/01b_1.jpg',url:'https://aroma.ru/brand/alfred-gratien/'},
 {id:3,name:'A. de Fussigny',type:'Коньяк',price:0,time:'Франция',desc:'Коньяк · premium selection',tone:'neroli',image:'https://aroma.ru/uploads/gss/brands/brand_icon_81.png',url:'https://aroma.ru/brand/a-de-fussigny/'},
 {id:4,name:'Santa Margherita',type:'Вино',price:0,time:'Италия',desc:'Итальянские вина · каталог бренда',tone:'tabac',image:'https://aroma.ru/uploads/gss/brands/brand_icon_17.png',url:'https://aroma.ru/brand/santa-margherita/'},
 {id:5,name:'Fontanafredda',type:'Вино',price:0,time:'Италия',desc:'Пьемонт · винодельческое хозяйство',tone:'moss',image:'https://aroma.ru/uploads/gss/brands/brand_icon_32.png',url:'https://aroma.ru/brand/fontanafredda/'},
 {id:6,name:'Bollinger',type:'Шампанское',price:0,time:'Франция',desc:'Шампанский дом · коллекция бренда',tone:'rain',image:'https://aroma.ru/uploads/gss/brands/brand_icon_187.png',url:'https://aroma.ru/brand/bollinger/'}
];
let cart=JSON.parse(localStorage.getItem('aroma-cart')||'[]'), wishes=JSON.parse(localStorage.getItem('aroma-wishes')||'[]'), filter='all';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function money(n){return n? n.toLocaleString('ru-RU')+' ₽':'По запросу'}
function save(){localStorage.setItem('aroma-cart',JSON.stringify(cart));localStorage.setItem('aroma-wishes',JSON.stringify(wishes));updateCounts()}
function updateCounts(){let count=cart.reduce((a,x)=>a+x.qty,0);$('#cartCount').textContent=count;$('#drawerCount').textContent=`${count} ${count===1?'предмет':'предметов'}`;$('#wishCount').textContent=wishes.length}
function renderProducts(){let list=filter==='all'?products:products.filter(p=>p.type===filter);$('#products').innerHTML=list.map(p=>`<article class="product-card"><a href="${p.url}" target="_blank" rel="noreferrer" class="product-visual ${p.tone}"><span class="tag">${p.type}</span><button class="heart ${wishes.includes(p.id)?'liked':''}" data-wish="${p.id}">${wishes.includes(p.id)?'♥':'♡'}</button><img class="brand-image" src="${p.image}" alt="${p.name}" loading="lazy"><div class="prod-object">AROMA<small>${p.desc.replaceAll(' · ',' / ')}</small></div></a><div class="prod-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="prod-meta"><span>${p.time}</span><span class="prod-price">По запросу</span></div><button class="quick-add" data-add="${p.id}">Добавить в подборку +</button></div></article>`).join('')}
function renderCart(){if(!cart.length){$('#cartItems').innerHTML='<div style="padding:50px 0;color:#777;line-height:1.7">Подборка пока пуста.<br>Добавьте бренды, которые хотите обсудить с менеджером.</div>'}else $('#cartItems').innerHTML=cart.map(x=>{let p=products.find(y=>y.id===x.id);return `<div class="cart-line"><div class="cart-thumb"><img src="${p.image}" alt=""></div><div style="flex:1"><h4>${p.name}</h4><p>Условия и цена — по запросу</p><div class="qty"><button data-dec="${p.id}">−</button>${x.qty}<button data-inc="${p.id}">+</button><button data-remove="${p.id}" style="float:right;color:#a85d43">Удалить</button></div></div></div>`}).join('');$('#cartTotal').textContent='По запросу';$('#progressBar').style.width='100%';$('#shippingText').textContent='Менеджер подготовит предложение по вашей подборке'}
function add(id){let found=cart.find(x=>x.id===id);found?found.qty++:cart.push({id,qty:1});save();renderCart();toast('Добавлено в корзину');$('#cartDrawer').classList.add('open');$('#overlay').classList.add('show')}
function toast(text){let t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
const ageGate=$('#ageGate');if(localStorage.getItem('aroma-age-confirmed')==='yes')ageGate.classList.add('hidden');$('#ageYes').onclick=()=>{localStorage.setItem('aroma-age-confirmed','yes');ageGate.classList.add('hidden')};$('#ageNo').onclick=()=>{window.location.href='https://www.google.com/';};
function closeAll(){$('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('show');$$('.modal').forEach(x=>x.classList.remove('open'))}
renderProducts();renderCart();updateCounts();
document.addEventListener('click',e=>{let addBtn=e.target.closest('[data-add]'), wish=e.target.closest('[data-wish]');if(addBtn)add(+addBtn.dataset.add);if(wish){let id=+wish.dataset.wish;wishes.includes(id)?wishes=wishes.filter(x=>x!==id):wishes.push(id);save();renderProducts();toast(wishes.includes(id)?'Сохранено в избранное':'Удалено из избранного')}let inc=e.target.closest('[data-inc]'),dec=e.target.closest('[data-dec]'),rem=e.target.closest('[data-remove]');if(inc){cart.find(x=>x.id===+inc.dataset.inc).qty++;save();renderCart()}if(dec){let x=cart.find(x=>x.id===+dec.dataset.dec);x.qty--;if(x.qty<1)cart=cart.filter(y=>y.id!==x.id);save();renderCart()}if(rem){cart=cart.filter(x=>x.id!==+rem.dataset.remove);save();renderCart()}});
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderProducts()});
$('#cartBtn').onclick=()=>{$('#cartDrawer').classList.add('open');$('#overlay').classList.add('show')};$('#overlay').onclick=closeAll;$('.close').onclick=closeAll;$$('.modal-close').forEach(b=>b.onclick=closeAll);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll()});
const quizSteps=[['Какая категория вам нужна?',['Вино','Шампанское','Коньяк','Крепкие напитки']],['Для какого формата?',['Ресторан и HoReCa','Бутик и ритейл','Частная коллекция','Корпоративный заказ']],['Что важно в поставщике?',['Эксклюзивный бренд','Стабильные поставки','Широкий каталог','Персональные условия']]];let qStep=0,qAnswers=[];function drawQuiz(){if(qStep<3){let s=quizSteps[qStep];$('#quiz').innerHTML=`<p class="eyebrow">Подбор поставки · 0${qStep+1} / 03</p><h2>${s[0]}</h2><div class="quiz-options">${s[1].map((x,i)=>`<button class="quiz-option" data-answer="${i}">${x}<span style="float:right">↗</span></button>`).join('')}</div>`}else{$('#quiz').innerHTML=`<p class="eyebrow">Ваш следующий шаг</p><h2>Каталог и<br><em>условия поставки</em></h2><p>Подбор ассортимента зависит от категории, формата клиента и условий сотрудничества. Оставьте запрос для получения актуального прайс-листа.</p><a class="btn btn-dark" href="mailto:info@aroma.ru?subject=Запрос%20по%20ассортименту">Запросить прайс-лист ↗</a>`}}$('#quizOpen').onclick=()=>{$('#quizModal').classList.add('open');$('#overlay').classList.add('show');qStep=0;drawQuiz()};$('#quiz').onclick=e=>{if(e.target.closest('[data-answer]')){qAnswers.push(e.target.closest('[data-answer]').dataset.answer);qStep++;drawQuiz()}};
$('#b2bOpen').onclick=()=>{$('#b2bModal').classList.add('open');$('#overlay').classList.add('show')};$('.submit-form').onclick=()=>{const inputs=$$('.form-box input');if([...inputs].some(x=>!x.value.trim()))return toast('Укажите имя и контакт для ответа');window.location.href='mailto:info@aroma.ru?subject='+encodeURIComponent('Запрос о сотрудничестве')+'&body='+encodeURIComponent([...inputs].map(x=>x.value).join('\n'));toast('Открываем почтовый клиент. Заявка ещё не отправлена.')};$('#subscribe').onclick=()=>{let input=$('#email');if(input.validity.valid&&input.value){toast('Демо-промокод: AROMA10. Подписка пока не подключена.')}else toast('Введите корректный e-mail')};$('.checkout').onclick=()=>cart.length?toast('Оформление заказа пока не подключено. Оплата не принимается.'):toast('Корзина пуста');
