const products=[
 {id:1,name:'Cedar / Fig',type:'candle',price:4900,time:'55 часов',desc:'Кедр, инжир, сухая амбра',tone:'cedar'},
 {id:2,name:'Santal 04',type:'candle',price:5200,time:'60 часов',desc:'Сандал, ирис, мускус',tone:'santal'},
 {id:3,name:'Neroli Mist',type:'diffuser',price:4300,time:'4 месяца',desc:'Нероли, зелёный чай, мох',tone:'neroli'},
 {id:4,name:'Tabac / Vanilla',type:'candle',price:4900,time:'55 часов',desc:'Табак, ваниль, кожа',tone:'tabac'},
 {id:5,name:'Moss Garden',type:'diffuser',price:4500,time:'4 месяца',desc:'Мох, ветивер, дождь',tone:'moss'},
 {id:6,name:'Après Rain',type:'candle',price:4600,time:'45 часов',desc:'Бергамот, шалфей, кедр',tone:'rain'}
];
let cart=JSON.parse(localStorage.getItem('aroma-cart')||'[]'), wishes=JSON.parse(localStorage.getItem('aroma-wishes')||'[]'), filter='all';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function money(n){return n.toLocaleString('ru-RU')+' ₽'}
function save(){localStorage.setItem('aroma-cart',JSON.stringify(cart));localStorage.setItem('aroma-wishes',JSON.stringify(wishes));updateCounts()}
function updateCounts(){let count=cart.reduce((a,x)=>a+x.qty,0);$('#cartCount').textContent=count;$('#drawerCount').textContent=`${count} ${count===1?'предмет':'предметов'}`;$('#wishCount').textContent=wishes.length}
function renderProducts(){let list=filter==='all'?products:products.filter(p=>p.type===filter);$('#products').innerHTML=list.map(p=>`<article class="product-card"><div class="product-visual ${p.tone}"><span class="tag">${p.type==='candle'?'Свеча':'Диффузор'}</span><button class="heart ${wishes.includes(p.id)?'liked':''}" data-wish="${p.id}">${wishes.includes(p.id)?'♥':'♡'}</button><div class="prod-object">aroma<small>${p.desc.replaceAll(', ',' / ')}</small></div></div><div class="prod-info"><h3>${p.name}</h3><div class="prod-meta"><span>${p.time}</span><span class="prod-price">${money(p.price)}</span></div><button class="quick-add" data-add="${p.id}">В корзину +</button></div></article>`).join('')}
function renderCart(){if(!cart.length){$('#cartItems').innerHTML='<div style="padding:50px 0;color:#777;line-height:1.7">В корзине пока тихо.<br>Добавьте аромат, который станет вашим.</div>'}else $('#cartItems').innerHTML=cart.map(x=>{let p=products.find(y=>y.id===x.id);return `<div class="cart-line"><div class="cart-thumb"></div><div style="flex:1"><h4>${p.name}</h4><p>${money(p.price)}</p><div class="qty"><button data-dec="${p.id}">−</button>${x.qty}<button data-inc="${p.id}">+</button><button data-remove="${p.id}" style="float:right;color:#a85d43">Удалить</button></div></div></div>`}).join('');let total=cart.reduce((a,x)=>a+products.find(p=>p.id===x.id).price*x.qty,0);$('#cartTotal').textContent=money(total);let percent=Math.min(total/7000*100,100);$('#progressBar').style.width=percent+'%';$('#shippingText').textContent=total>=7000?'Доставка для вас бесплатна':'Добавьте ещё '+money(7000-total)+' для бесплатной доставки'}
function add(id){let found=cart.find(x=>x.id===id);found?found.qty++:cart.push({id,qty:1});save();renderCart();toast('Добавлено в корзину');$('#cartDrawer').classList.add('open');$('#overlay').classList.add('show')}
function toast(text){let t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function closeAll(){$('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('show');$$('.modal').forEach(x=>x.classList.remove('open'))}
renderProducts();renderCart();updateCounts();
document.addEventListener('click',e=>{let addBtn=e.target.closest('[data-add]'), wish=e.target.closest('[data-wish]');if(addBtn)add(+addBtn.dataset.add);if(wish){let id=+wish.dataset.wish;wishes.includes(id)?wishes=wishes.filter(x=>x!==id):wishes.push(id);save();renderProducts();toast(wishes.includes(id)?'Сохранено в избранное':'Удалено из избранного')}let inc=e.target.closest('[data-inc]'),dec=e.target.closest('[data-dec]'),rem=e.target.closest('[data-remove]');if(inc){cart.find(x=>x.id===+inc.dataset.inc).qty++;save();renderCart()}if(dec){let x=cart.find(x=>x.id===+dec.dataset.dec);x.qty--;if(x.qty<1)cart=cart.filter(y=>y.id!==x.id);save();renderCart()}if(rem){cart=cart.filter(x=>x.id!==+rem.dataset.remove);save();renderCart()}});
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderProducts()});
$('#cartBtn').onclick=()=>{$('#cartDrawer').classList.add('open');$('#overlay').classList.add('show')};$('#overlay').onclick=closeAll;$('.close').onclick=closeAll;$$('.modal-close').forEach(b=>b.onclick=closeAll);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAll()});
const quizSteps=[['Какая атмосфера вам близка?',['Уютный вечер','Медитация и фокус','Романтика','Бодрость']],['Ваше ольфакторное семейство?',['Древесные и смолы','Табак и ваниль','Свежие травы','Инжир и цитрус']],['Для какого пространства?',['Гостиная','Спальня','Ванная комната','Рабочий кабинет']]];let qStep=0,qAnswers=[];function drawQuiz(){if(qStep<3){let s=quizSteps[qStep];$('#quiz').innerHTML=`<p class="eyebrow">Ваш аромат · 0${qStep+1} / 03</p><h2>${s[0]}</h2><div class="quiz-options">${s[1].map((x,i)=>`<button class="quiz-option" data-answer="${i}">${x}<span style="float:right">↗</span></button>`).join('')}</div>`}else{$('#quiz').innerHTML=`<p class="eyebrow">Ваш персональный выбор</p><h2>Cedar / <em>Fig</em></h2><p>Тёплая древесная композиция для пространства, где хочется остаться. Кедр, инжир и сухая амбра.</p><div class="total"><span>Свеча · 55 часов</span><strong>4 900 ₽</strong></div><button class="btn btn-dark" data-add="1">Добавить в корзину ↗</button>`}}$('#quizOpen').onclick=()=>{$('#quizModal').classList.add('open');drawQuiz()};$('#quiz').onclick=e=>{if(e.target.closest('[data-answer]')){qAnswers.push(e.target.closest('[data-answer]').dataset.answer);qStep++;drawQuiz()}};
$('#b2bOpen').onclick=()=>{$('#b2bModal').classList.add('open');$('#overlay').classList.add('show')};$('.submit-form').onclick=()=>{const inputs=$$('.form-box input');if([...inputs].some(x=>!x.value.trim()))return toast('Укажите имя и контакт для ответа');window.location.href='mailto:info@aroma.ru?subject='+encodeURIComponent('Запрос о сотрудничестве')+'&body='+encodeURIComponent([...inputs].map(x=>x.value).join('\n'));toast('Открываем почтовый клиент. Заявка ещё не отправлена.')};$('#subscribe').onclick=()=>{let input=$('#email');if(input.validity.valid&&input.value){toast('Демо-промокод: AROMA10. Подписка пока не подключена.')}else toast('Введите корректный e-mail')};$('.checkout').onclick=()=>cart.length?toast('Оформление заказа пока не подключено. Оплата не принимается.'):toast('Корзина пуста');
